# create root .my.cnf config file
- name: Add .my.cnf
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600

# Set root password
# UPDATE mysql.user SET Password=PASSWORD('mysecret') WHERE User='root';
# FLUSH PRIVILEGES;

- name: Determine required MySQL Python libraries.
  set_fact:
    deb_mysql_python_package: "{% if 'python3' in ansible_python_interpreter|default('') %}python3-mysqldb{% else %}python-mysqldb{% endif %}"

- name: Ensure MySQL Python libraries are installed.
  apt: "name={{ deb_mysql_python_package }} state=present"

- name: Set root Password
  mysql_user: 
    login_password: '{{ mysql_password }}'
    check_implicit_admin: yes
    name: '{{ mysql_user }}'
    host: '{{ item }}'
    password: '{{ mysql_password }}'
    state: present 
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
  notify:
    - restart mysql
    
- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

#- name: Remove anonymous users
#  command: 'mysql -ne "{{ item }}"'
#  with_items:
#    - DELETE FROM mysql.user WHERE User=''
#  changed_when: False

- name: Remove anonymous users
  mysql_user:
    name: ''
    state: absent

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: copy db schema
  template:
    src: database.sql.j2
    dest: /tmp/database.sql 

- name: create nodes database
  mysql_db: 
    name: '{{mysql_db_name}}'
    state: present
  register: db_state

- name: create db table
  mysql_db: 
    name: '{{mysql_db_name}}'
    state: import
    target: /tmp/database.sql
  when: db_state.changed

- name: test database is absent
  mysql_db: 
    name: test
    state: absent
  notify:
    - restart mysql

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

  # By: https://github.com/PCextreme/ansible-role-mariadb/blob/master/tasks/mysql_secure_installation.yml