#!/usr/bin/ansible-playbook
---
- hosts: localhost
  gather_facts: yes
  become: yes
  roles:
  - AnsibleRole_DBservice


# ansible-playbook test_DBservice.yml --extra-vars "mysql_root_password=your_very_secret_password"
